name: clean
description: Cleans the workspace ridding unnecessary files
inputs:
  preserve_output:
    description: 'Whether to preserve output directories'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - run: |
        cd submission
        rm -rf __MACOSX coverage types yarn.lock package-lock.json \
        *.md .turbo .vscode .idea .gitignore .gitkeep .babelrc;
        if [ ${{ inputs.preserve_output }} = "false" ]; then
          rm -rf out dist .git
        else
          rm -rf pnpm-lock.yaml
        fi
      shell: bash
