name: Run Staging Tests
run-name: '[${{ github.event.client_payload.question_name }} / ${{ github.event.client_payload.name }}] - ${{ github.event.client_payload.submission_id }}'

on:
  repository_dispatch:
    types: [run-staging-tests]

jobs:
  staging-test:
    name: Staging
    uses: ./.github/workflows/test.yml
    with:
      application_environment: STAGING
    secrets: inherit
