name: Run Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/bootstrap
      
      - name: Echo client payload
        run: echo "${{ toJson(github.event.client_payload) }}"

      - name: Call Test Script
        id: test
        run: |
          node scripts/test.js --payload "${{ toJson(github.event.client_payload) }}"

      - name: Email Workflow URL
        run: |
          sudo apt-get install mailutils
          echo "Check out the workflow run at - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" | mail -s "Workflow URL" it21072642@my.sliit.lk
