name: Run Production Tests
run-name: '[${{ github.event.client_payload.question_name }} / ${{ github.event.client_payload.name }}] - ${{ github.event.client_payload.submission_id }}'

on:
  repository_dispatch:
    types: [run-production-tests]

jobs:
  live-test:
    name: Production
    uses: ./.github/workflows/test.yml
    secrets: inherit
