name: Run Staging Tests
run-name: 'Evalutate submission - ${{ github.event.client_payload.submission_id }}'

on:
  repository_dispatch:
    types: [run-staging-tests]

jobs:
  staging-test:
    name: Staging
    uses: ./.github/workflows/test.yml
    with:
      application_environment: STAGING
    secrets: inherit
